### ISSUE TITLE
Feature Request: Hooks to extend `mob` by running custom commands

### ISSUE THREAD

**Issue by lorenzleutgeb** [remotemobprogramming/mob#426] opened 2024-05-02 15:33 UTC
I'd like to execute one command when it is my turn as a typist, i.e. right after I did `mob start`, and another right after I handed over, i.e. after `mob next` or `mob done`.

The hook should only be executed if these commands ran successfully.

Preferably I'd set environment variables like `MOB_START_HOOK_AFTER`, `MOB_NEXT_HOOK_AFTER`, `MOB_DONE_HOOK_AFTER` or so. In my case I'd actually set the latter two to the same value. The suffix `_AFTER` might look strange, but is there for forward compatibility in case someone wants to get a hook `_BEFORE` things happen.

---

cc @mightyiam @jleightcap we could hook `systemctl --user (start|stop) cachix-watch-store@ngi`.

**Comment by hollesse** [comment] 2024-05-03 13:42
Hi @lorenzleutgeb thank you for your contribution with creating this issue. This issue is a duplicate of #266. Please have a look there and comment on this issue. If you like you can also join our [slack community](http://slack.mob.sh).

**Closed by hollesse** 2024-05-03 13:42 UTC
Labels: duplicate
